Repository OCA/apps-store, pull requests merged in 2018-10, with the labels that each got.

#17 [11.0] Show a default 'OCA' icon on product in webshop
  website_apps_store/static/src/img/oca.png
  website_apps_store/views/templates.xml
Labels: needs review

#18 [FIX] download file name Fix
  apps_download/__manifest__.py
  apps_download/models/product_product.py
  website_apps_store/controllers/main.py
Labels: needs review

#22 [FIX] solve problem in case of multiple version for the one module
  apps_product_creator/__manifest__.py
  apps_product_creator/models/odoo_module.py
Labels: approved

#23 [ADD] website_apps_store: new PDP layout.
  website_apps_store/static/src/css/main.less
  website_apps_store/views/assets.xml
  website_apps_store/views/templates.xml
Labels: needs review

#24 [IMP] Autopublish the modules on the website
  apps_product_creator/README.rst
  apps_product_creator/__manifest__.py
  apps_product_creator/models/odoo_module.py
  apps_product_creator/readme/HISTORY.rst
  apps_product_creator/static/description/index.html
Labels: approved

#25 [11.0] remove default icon for products in the shop
  website_apps_store/__manifest__.py
  website_apps_store/static/src/img/oca.png
  website_apps_store/views/templates.xml
Labels: approved

#36 [IMP] while clean the odoo module version archive the product
  apps_product_creator/__manifest__.py
  apps_product_creator/models/__init__.py
  apps_product_creator/models/odoo_module_version.py
Labels: approved, needs review
